version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - client_data:/var/lib/mysql
    restart: always
  sonarqube:
    container_name: sonar_webflux
    image: sonarqube
    ports:
      - "9000:9000"
volumes:
  client_data:
  sonarqube:
